### ISSUE TITLE
VS 2015 Support

### ISSUE THREAD

**Issue by NickHardeman** [NickHardeman/ofxFBX#5]
Attempting to get VS 2015 support. @jasonrwalters did you try running the example from the example folder in Release in 64 bit mode?

**Comment by rootux** [comment]
@NickHardeman Did it worked for you? It says it only support osx. did it worked on windows?

**Comment by NickHardeman** [comment]
It works for me locally. But not sure how it fairs on git. Let me know if you need any help getting it working on windows.

**Comment by ghost** [comment]
Sorry, been swamped - just tried and no worky.  My quick guess is that the class isn't linked in the project because the example states:

Severity    Code    Description Project File    Line    Suppression State
Error   C1083   Cannot open source file: '..\src\ofxFBXCluster.cpp': No such file or directory  emptyExample    C:\Dev\of\apps\myApps\example-ImporterAnimations\c1xx   1

**Comment by NickHardeman** [comment]
VS 2017 is now supported in OF 0.10.0
